In [11]:
import pandas as pd

raw_pairs_df = pd.read_csv("/kaggle/input/datasets/amirsafarzadeh8203/raw-pairs-v10k/raw_pairs_v10k.csv")
print("تعداد کل ردیف‌ها:", len(raw_pairs_df))
print(raw_pairs_df.nunique())

تعداد کل ردیف‌ها: 9759
path           9759
sentence       8154
raw_whisper    9140
dtype: int64

In [12]:
pair_dupes = raw_pairs_df.duplicated(subset=["sentence", "raw_whisper"], keep=False)
print("تعداد ردیف‌هایی که جفت (sentence, raw_whisper) تکراریه:", pair_dupes.sum())

raw_pairs_df[pair_dupes].sort_values(["sentence", "raw_whisper"]).head(20)

تعداد ردیف‌هایی که جفت (sentence, raw_whisper) تکراریه: 1167

,path,sentence,raw_whisper
5250,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!از طرف سعیده. حشره عشق,از طرف سعیده، حشره عشق
6721,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!از طرف سعیده. حشره عشق,از طرف سعیده، حشره عشق
7675,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!از طرف سعیده. حشره عشق,از طرف سعیده، حشره عشق
2826,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!اون با من به گور میره,اون با من به گور میره
5369,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!اون با من به گور میره,اون با من به گور میره
8251,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!اون با من به گور میره,اون با من به گور میره
7320,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!بده به من! بزار برم,بده به من. بزار برم.
9743,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!بده به من! بزار برم,بده به من. بزار برم.
5794,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!حالا یه خواهر هم دارم,حالا یه خواهر هم دارم
9312,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!حالا یه خواهر هم دارم,حالا یه خواهر هم دارم
1184,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!دارم میرم تو تلویزیون,دارم میرم تو تلویزیون
3910,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!دارم میرم تو تلویزیون,دارم میرم تو تلویزیون
3923,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,.از این جور مضخرفات,از این جور مضخرفات
9183,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,.از این جور مضخرفات,از این جور مضخرفات
1377,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,.اون دینا هستش نه جینا,اون دینا هستش نه جینا
2657,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,.اون دینا هستش نه جینا,اون دینا هستش نه جینا
835,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,.اون واسه دبیرستان بود,اون واسه دبیرستان بود
5912,common_voice_fa_18786818.mp3,.اون واسه دبیرستان بود,اون واسه دبیرستان بود
1238,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,.اونا آخر درست حسابین,اونا آخر درست حسابین
3606,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,.اونا آخر درست حسابین,اونا آخر درست حسابین

In [13]:
before = len(raw_pairs_df)
raw_pairs_df = raw_pairs_df.drop_duplicates(subset=["sentence", "raw_whisper"], keep="first")
after = len(raw_pairs_df)
print(f"{before} -> {after} ({before - after} ردیف duplicate واقعی حذف شد)")

9759 -> 9147 (612 ردیف duplicate واقعی حذف شد)

In [14]:
print("تعداد نهایی ردیف‌ها:", len(raw_pairs_df))
print(raw_pairs_df.nunique())
# اینجا طبیعیه که هنوز unique sentence از unique raw_whisper کمتر باشه
# چون یک جمله می‌تونه چند raw_whisper متفاوت (از گوینده‌های مختلف) داشته باشه — این یه باگ نیست

تعداد نهایی ردیف‌ها: 9147
path           9147
sentence       8154
raw_whisper    9140
dtype: int64

In [15]:
dup_whisper = raw_pairs_df[raw_pairs_df["raw_whisper"].duplicated(keep=False)]
dup_whisper.sort_values("raw_whisper")

,path,sentence,raw_whisper
4013,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,انها پادشاه را در برابر تندیس الهه خود بستند,آنها پادشاه را در برابر تندیس الهه خود بستند.
5124,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,آنها پادشاه را در برابر تندیس الهه خود بستند,آنها پادشاه را در برابر تندیس الهه خود بستند.
349,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,اوقات خوشی داشته باشی,اوقات خوشی داشته باشی
3313,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,اوقات خوشی داشته باشی!,اوقات خوشی داشته باشی
3329,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,بدون آنکه باز سوالی کرده باشم با عصبانیت شروع کرد,بدون آنکه باز سوالی کرده باشم با عصبانیت شروع کرد
6072,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,بدون انکه باز سوالی کرده باشم با عصبانیت شروع کرد,بدون آنکه باز سوالی کرده باشم با عصبانیت شروع کرد
7566,common_voice_fa_26960884.mp3,سفر به خیر!,سفر به خیر
8450,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,سفر به خیر,سفر به خیر
4434,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!من باید از اینجا برم,من باید از اینجا برم
7115,common_voice_fa_18206951.mp3,!من بايد از اينجا برم,من باید از اینجا برم
450,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,من بودایی هستم,من بودایی هستم.
4709,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,من بودایی هستم.,من بودایی هستم.
1321,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,کيبوردم دم دست نيست,کیبوردم دم دست نیست
6335,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,کیبوردم دم دست نیست,کیبوردم دم دست نیست

In [16]:
whisper_dupes = raw_pairs_df["raw_whisper"].duplicated(keep=False)
print("تعداد ردیف‌هایی که raw_whisper مشترک با ردیف دیگه‌ای داره:", whisper_dupes.sum())

raw_pairs_df[whisper_dupes].sort_values("raw_whisper")

تعداد ردیف‌هایی که raw_whisper مشترک با ردیف دیگه‌ای داره: 14

,path,sentence,raw_whisper
4013,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,انها پادشاه را در برابر تندیس الهه خود بستند,آنها پادشاه را در برابر تندیس الهه خود بستند.
5124,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,آنها پادشاه را در برابر تندیس الهه خود بستند,آنها پادشاه را در برابر تندیس الهه خود بستند.
349,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,اوقات خوشی داشته باشی,اوقات خوشی داشته باشی
3313,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,اوقات خوشی داشته باشی!,اوقات خوشی داشته باشی
3329,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,بدون آنکه باز سوالی کرده باشم با عصبانیت شروع کرد,بدون آنکه باز سوالی کرده باشم با عصبانیت شروع کرد
6072,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,بدون انکه باز سوالی کرده باشم با عصبانیت شروع کرد,بدون آنکه باز سوالی کرده باشم با عصبانیت شروع کرد
7566,common_voice_fa_26960884.mp3,سفر به خیر!,سفر به خیر
8450,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,سفر به خیر,سفر به خیر
4434,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,!من باید از اینجا برم,من باید از اینجا برم
7115,common_voice_fa_18206951.mp3,!من بايد از اينجا برم,من باید از اینجا برم
450,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,من بودایی هستم,من بودایی هستم.
4709,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,من بودایی هستم.,من بودایی هستم.
1321,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,کيبوردم دم دست نيست,کیبوردم دم دست نیست
6335,/tmp/common_voice_fa_extracted/cv-corpus-26.0-...,کیبوردم دم دست نیست,کیبوردم دم دست نیست

In [17]:
before = len(raw_pairs_df)
raw_pairs_df = raw_pairs_df[~raw_pairs_df["raw_whisper"].duplicated(keep=False)]
after = len(raw_pairs_df)
print(f"{before} -> {after} ({before - after} ردیف حذف شد)")

9147 -> 9133 (14 ردیف حذف شد)

In [18]:
raw_pairs_df = raw_pairs_df.reset_index(drop=True)
print("تعداد نهایی ردیف‌ها:", len(raw_pairs_df))
print(raw_pairs_df.nunique())

تعداد نهایی ردیف‌ها: 9133
path           9133
sentence       8142
raw_whisper    9133
dtype: int64

In [19]:
raw_pairs_df.to_csv("/kaggle/working/raw_pairs_v10k_cleaned.csv", index=False)
print("ذخیره شد:", raw_pairs_df.shape)

ذخیره شد: (9133, 3)